using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Web;

namespace ACMS.ApplicationBase
{
    public class ServiceBase : IDisposable
    {
        private List<IDisposable> DisposableObjList = new List<IDisposable>();

        protected DbContext CreateDbContext()
        {
            DbContext obj = new ACMS.EF.ACMSEFEntities();

            string connString = ConfigurationManager.ConnectionStrings["ACMSConnectionString"].ToString();

            obj.Database.CommandTimeout = 36000;
            obj.Database.Connection.ConnectionString = connString;
#if DEBUG
            //print sql generated by Entity framework
            obj.Database.Log = x => Debug.Write(x);
#endif
            return obj;
        }

        protected void AddDisposableObject(IDisposable obj)
        {
            DisposableObjList.Add(obj);
        }

        public void Dispose()
        {
            foreach (var obj in DisposableObjList)
            {
                if (obj != null)
                {
                    obj.Dispose();
                }
            }
        }
    }
}