//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACMSEFEntities : DbContext
    {
        public ACMSEFEntities()
            : base("name=ACMSEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<RoleMenu> RoleMenu { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<AirTimeAlarmSet> AirTimeAlarmSet { get; set; }
        public virtual DbSet<PlanesTCtrlItem_ReList> PlanesTCtrlItem_ReList { get; set; }
        public virtual DbSet<WatchPrintList> WatchPrintList { get; set; }
        public virtual DbSet<V_DailyRecordReport> V_DailyRecordReport { get; set; }
        public virtual DbSet<ReportRecord> ReportRecord { get; set; }
        public virtual DbSet<V_RecordMonthReport> V_RecordMonthReport { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<ExecuteUnit> ExecuteUnit { get; set; }
        public virtual DbSet<CESSNA172RDailyRecord> CESSNA172RDailyRecord { get; set; }
        public virtual DbSet<PA44_180DailyRecord> PA44_180DailyRecord { get; set; }
        public virtual DbSet<Planes> Planes { get; set; }
        public virtual DbSet<V_Planes> V_Planes { get; set; }
        public virtual DbSet<V_EngineReport> V_EngineReport { get; set; }
        public virtual DbSet<PlaneType> PlaneType { get; set; }
        public virtual DbSet<PlTypeTCtrlList> PlTypeTCtrlList { get; set; }
        public virtual DbSet<PlTypeTCtrlList_Log> PlTypeTCtrlList_Log { get; set; }
        public virtual DbSet<V_PlTypeTCtrlList> V_PlTypeTCtrlList { get; set; }
        public virtual DbSet<V_V_PlTypeTCtrlList_Log> V_V_PlTypeTCtrlList_Log { get; set; }
        public virtual DbSet<PlanesTCtrlItem> PlanesTCtrlItem { get; set; }
        public virtual DbSet<V_PlanesTCtrlItem> V_PlanesTCtrlItem { get; set; }
        public virtual DbSet<V_PlanesTCtrlItem_Check> V_PlanesTCtrlItem_Check { get; set; }
        public virtual DbSet<V_PlanesTCtrlItem_Log> V_PlanesTCtrlItem_Log { get; set; }
    }
}
