//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirTimeAlarmSet
    {
        public string ID { get; set; }
        public Nullable<decimal> Days { get; set; }
        public Nullable<decimal> ReNewAirTime { get; set; }
        public Nullable<decimal> ReNewUpTempTime { get; set; }
        public Nullable<int> ReNewOnOffTime { get; set; }
        public bool IsActive { get; set; }
        public string CreateTime { get; set; }
        public string Creator { get; set; }
        public string UpdateTime { get; set; }
        public string Updator { get; set; }
    }
}
