//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CESSNA172RDailyRecord
    {
        public string ID { get; set; }
        public int Type { get; set; }
        public string PlanID { get; set; }
        public string InputDate { get; set; }
        public decimal DayClearingTime { get; set; }
        public int DayRiseAndFallNum { get; set; }
        public decimal DayAirTime { get; set; }
        public decimal DayMaintenaceTime { get; set; }
        public decimal CorrectClearingTime { get; set; }
        public decimal CorrectAirTime { get; set; }
        public Nullable<decimal> PlanNewClearingTime { get; set; }
        public Nullable<decimal> PlanNewAirTime { get; set; }
        public Nullable<int> PlanNewRiseAndFallNum { get; set; }
        public Nullable<decimal> PlanDayClearingTime { get; set; }
        public Nullable<decimal> PlanDayAirTime { get; set; }
        public Nullable<decimal> PlanDayGroundTime { get; set; }
        public string EngineType { get; set; }
        public string EngineNo { get; set; }
        public string EngineCorrectTSO { get; set; }
        public Nullable<decimal> EngineNewTSN { get; set; }
        public string ExecUnit { get; set; }
        public string Memo { get; set; }
        public bool IsActive { get; set; }
        public string CreateTime { get; set; }
        public string Creator { get; set; }
        public string UpdateTime { get; set; }
        public string Updator { get; set; }
    }
}
