//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanesTCtrlItem_ReList
    {
        public string PlanesTCtrlItemID { get; set; }
        public string PlTypeTCtrl { get; set; }
    }
}
