//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanesTCtrlItem
    {
        public string ID { get; set; }
        public string PlaneTypeID { get; set; }
        public string PlaneNo { get; set; }
        public bool IsCtrl { get; set; }
        public string JianNO { get; set; }
        public string SerialNO { get; set; }
        public Nullable<decimal> TSN { get; set; }
        public Nullable<decimal> TSO { get; set; }
        public Nullable<int> ExeCapacity { get; set; }
        public Nullable<bool> IsWatDate { get; set; }
        public Nullable<bool> IsWatAirTime { get; set; }
        public Nullable<bool> IsWatOnOffTime { get; set; }
        public Nullable<bool> IsWatUpTemprTime { get; set; }
        public string FCheckDate { get; set; }
        public Nullable<decimal> FAirTime { get; set; }
        public Nullable<int> FOnOffTime { get; set; }
        public Nullable<decimal> FUpTemprTime { get; set; }
        public string RCheckDate { get; set; }
        public Nullable<decimal> RAirTime { get; set; }
        public Nullable<int> ROnOffTime { get; set; }
        public Nullable<decimal> RUpTemprTime { get; set; }
        public string Memo { get; set; }
        public bool IsActive { get; set; }
        public string CreateTime { get; set; }
        public string Creator { get; set; }
        public string UpdateTime { get; set; }
        public string Updator { get; set; }
    }
}
