//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EngineReport
    {
        public string ID { get; set; }
        public int Type { get; set; }
        public string PlanID { get; set; }
        public string InputDate { get; set; }
        public string EngineType { get; set; }
        public string EngineNo { get; set; }
        public Nullable<decimal> EngineCorrectTSO { get; set; }
        public Nullable<decimal> EngineNewTSN { get; set; }
        public bool IsActive { get; set; }
        public string CreateTime { get; set; }
        public string Creator { get; set; }
        public string UpdateTime { get; set; }
        public string Updator { get; set; }
        public string Position { get; set; }
        public string PlaneNo { get; set; }
        public Nullable<decimal> PlanDayAirTime { get; set; }
        public string TypeName { get; set; }
    }
}
