//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Planes
    {
        public string ID { get; set; }
        public string PlaneTypeID { get; set; }
        public string PlaneNo { get; set; }
        public string PlaneSeria { get; set; }
        public string PlaneFacDate { get; set; }
        public bool IsMonitored { get; set; }
        public string Memo { get; set; }
        public int RankNo { get; set; }
        public bool IsActive { get; set; }
        public string CreateTime { get; set; }
        public string Creator { get; set; }
        public string UpdateTime { get; set; }
        public string Updator { get; set; }
        public string TypeName { get; set; }
    }
}
