
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACMS.EF
{

using System;
    using System.Collections.Generic;
    
public partial class V_Planes
{

    public string ID { get; set; }

    public string PlaneTypeID { get; set; }

    public string PlaneNo { get; set; }

    public string PlaneSeria { get; set; }

    public string PlaneFacDate { get; set; }

    public bool IsMonitored { get; set; }

    public string Memo { get; set; }

    public int RankNo { get; set; }

    public bool IsActive { get; set; }

    public string CreateTime { get; set; }

    public string Creator { get; set; }

    public string UpdateTime { get; set; }

    public string Updator { get; set; }

    public string TypeName { get; set; }

}

}
